### ISSUE TITLE
Saving and deleting

### ISSUE THREAD

**Issue by AdeebNqo** [einstein07/ToCTeditor#1]
I've managed to run the interface. There are two things that are still missing before creating and plugging the backed.

![Screenshot from 2021-11-24 21-03-28](https://user-images.githubusercontent.com/2272078/143299046-8b67270e-2a15-4d83-a233-4e1e0141060f.png)

Consider the above interface and its associated 'template parts' that are loaded for testing purposes:

1. There is no way to save the template
2. The menu bar for each template item has not been implemented (I suspect this has to do with the 'error Couldn't find file: /images/kebab30.png' that I am getting).
3. You do not need to create models for the various template parts (e.g., Copula.java). The 'GrammarEngineBase' module in https://github.com/AdeebNqo/NguniTextGeneration/ already has them. I've already created an issue on that repo for updating the readme file. I know that issue is dated Oct but I will update the readme file tomorrow to add instructions for compiling the modules and importing the various models.

**Comment by einstein07** [comment]
1. A Save button has been added.
2. Yes, that is correct -- the jre could not load the kebab menu icon which provides the said menu options
3. The GrammarEngineBase library is now being used.
Closing this issue.
