### ISSUE TITLE
Opening an existing template

### ISSUE THREAD

**Issue by AdeebNqo** [einstein07/ToCTeditor#3]
On the following screen:

![Screenshot from 2021-11-25 18-08-10](https://user-images.githubusercontent.com/2272078/143473666-882f66d9-91ae-4eb7-85d5-9f9a2c6350f8.png)

Would it be possible to add another box below the existing one for allowing one to open an existing template?

**Comment by einstein07** [comment]
This has been added. Closing this issue now.
