### ISSUE TITLE
The makefile is not building/including the required template parsing libraries

### ISSUE THREAD

**Issue by AdeebNqo** [einstein07/ToCTeditor#4]
The makefile does not automatically load the necessary jar files.

![Screenshot from 2021-12-03 19-09-37](https://user-images.githubusercontent.com/2272078/144644033-829e8df4-9f39-4096-909f-79c666e59cd4.png)

Perhaps they could be packaged as part of the code?

**Comment by AdeebNqo** [comment]
This has been resolved in the branch https://github.com/einstein07/ToCTeditor/tree/fixing_makefile_and_testing_newjar
 
Please review, merge it, and fix the issues pertaining to the DataModel.java class

**Comment by einstein07** [comment]
The DataModel class was fixed on Friday - as well as the review and merge. Will close the issue now.
