### ISSUE TITLE
Creating polymorphic word not working

### ISSUE THREAD

**Issue by AdeebNqo** [einstein07/ToCTeditor#7]
When creating a polymorphic word, the interface allows one to choose the various items that make up the word. See:

![PolyWord](https://user-images.githubusercontent.com/2272078/145963014-2eed0932-9474-47db-9e42-0b8b26064dc7.png)

1. It does not recognise the root type
2. After clicking 'create', the rendering of the polymorphic word does not show the 'items' of the word.
3. I am unable to specify the name of the new word.

**Comment by einstein07** [comment]
Numbers 1 and 2 have been fixed.

So, concerning number 3, you will see that when you create a template (or word) portion it is by default given a serialized name - unique to it - this can now be changed using the dedicated name text field. This is still being implemented for all the different template models and other field attributes.
