### ISSUE TITLE
TTL preview

### ISSUE THREAD

**Issue by AdeebNqo** [einstein07/ToCTeditor#9]
When clicking a template fragment, the Item turtle preview renders fine. See:

![TTLPreview](https://user-images.githubusercontent.com/2272078/145964172-a821fe65-5c1c-43de-8647-2a8489d89cc5.png)

However, when no item is clicked, or when an item has been unselected, the preview must render the entire template.

**Comment by einstein07** [comment]
This issue is addressed by the latest commit.
